apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-dep
    c: true
  name: my-dep
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: my-dep
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: my-dep
    spec:
      containers:
      - command:
        - sleep
        - "99999"
        image: busybox
        imagePullPolicy: Always
        name: busybox