apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-dep
    c: true
    d: 1
  name: my-dep
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: my-dep
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: my-dep
    spec:
      containers:
      - command:
        - sleep
        - "99999"
        image: busybox
        imagePullPolicy: Always
        name: busybox
---
apiVersion: batch/v1
kind: Job
metadata:
  name: pi
spec:
  suspend: true
  template:
    spec:
      containers:
      - name: pi
        image: perl:5.34.0
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
  backoffLimit: 4